name: README build

on:
  push:
    branches:
      - master
      - main
  schedule:
    - cron: '0 */3 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OPEN_WEATHER_MAP_KEY: ${{ secrets.OPEN_WEATHER_MAP_KEY }}
      CITY_NAME: ${{ vars.CITY_NAME }}
      TIMEZONE: ${{ vars.TIMEZONE }}
      INSTAGRAM_ACCOUNT: ${{ vars.INSTAGRAM_ACCOUNT }}
      HTTP_PROXY: ${{ vars.HTTP_PROXY }}

    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - name: cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-js-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        run: npm install
      - name: Generate README file
        run: node index.js
      - name: Commit & push README.md
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(readme): auto-update README.md"
          file_pattern: README.md
